#include "libc/ctype.h"

/**
 * Original name: __MojiStat
 */
unsigned char __MojiStat[0x101] = {
    0,
    /* 0x00 ''   */ CTYPE_ISCONTROL,
    /* 0x01 ''   */ CTYPE_ISCONTROL,
    /* 0x02 ''   */ CTYPE_ISCONTROL,
    /* 0x03 ''   */ CTYPE_ISCONTROL,
    /* 0x04 ''   */ CTYPE_ISCONTROL,
    /* 0x05 ''   */ CTYPE_ISCONTROL,
    /* 0x06 ''   */ CTYPE_ISCONTROL,
    /* 0x07 ''   */ CTYPE_ISCONTROL,
    /* 0x08 ''   */ CTYPE_ISCONTROL,
    /* 0x09 '\t' */ CTYPE_ISCONTROL | CTYPE_ISSPACE,
    /* 0x0A '\n' */ CTYPE_ISCONTROL | CTYPE_ISSPACE,
    /* 0x0B ''   */ CTYPE_ISCONTROL | CTYPE_ISSPACE,
    /* 0x0C '\f' */ CTYPE_ISCONTROL | CTYPE_ISSPACE,
    /* 0x0D '\r' */ CTYPE_ISCONTROL | CTYPE_ISSPACE,
    /* 0x0E ''   */ CTYPE_ISCONTROL,
    /* 0x0F ''   */ CTYPE_ISCONTROL,
    /* 0x10 ''   */ CTYPE_ISCONTROL,
    /* 0x11 ''   */ CTYPE_ISCONTROL,
    /* 0x12 ''   */ CTYPE_ISCONTROL,
    /* 0x13 ''   */ CTYPE_ISCONTROL,
    /* 0x14 ''   */ CTYPE_ISCONTROL,
    /* 0x15 ''   */ CTYPE_ISCONTROL,
    /* 0x16 ''   */ CTYPE_ISCONTROL,
    /* 0x17 ''   */ CTYPE_ISCONTROL,
    /* 0x18 ''   */ CTYPE_ISCONTROL,
    /* 0x19 ''   */ CTYPE_ISCONTROL,
    /* 0x1A ''   */ CTYPE_ISCONTROL,
    /* 0x1B ''   */ CTYPE_ISCONTROL,
    /* 0x1C ''   */ CTYPE_ISCONTROL,
    /* 0x1D ''   */ CTYPE_ISCONTROL,
    /* 0x1E ''   */ CTYPE_ISCONTROL,
    /* 0x1F ''   */ CTYPE_ISCONTROL,
    /* 0x20 ' '  */ CTYPE_ISSPACE,
    /* 0x21 '!'  */ 0,
    /* 0x22 '"'  */ 0,
    /* 0x23 '#'  */ 0,
    /* 0x24 '$'  */ 0,
    /* 0x25 '%'  */ 0,
    /* 0x26 '&'  */ 0,
    /* 0x27 '\'' */ 0,
    /* 0x28 '('  */ 0,
    /* 0x29 ')'  */ 0,
    /* 0x2A '*'  */ 0,
    /* 0x2B '+'  */ 0,
    /* 0x2C ','  */ 0,
    /* 0x2D '-'  */ 0,
    /* 0x2E '.'  */ 0,
    /* 0x2F '/'  */ 0,
    /* 0x30 '0'  */ CTYPE_ISDIGIT | CTYPE_ISXDIGIT,
    /* 0x31 '1'  */ CTYPE_ISDIGIT | CTYPE_ISXDIGIT,
    /* 0x32 '2'  */ CTYPE_ISDIGIT | CTYPE_ISXDIGIT,
    /* 0x33 '3'  */ CTYPE_ISDIGIT | CTYPE_ISXDIGIT,
    /* 0x34 '4'  */ CTYPE_ISDIGIT | CTYPE_ISXDIGIT,
    /* 0x35 '5'  */ CTYPE_ISDIGIT | CTYPE_ISXDIGIT,
    /* 0x36 '6'  */ CTYPE_ISDIGIT | CTYPE_ISXDIGIT,
    /* 0x37 '7'  */ CTYPE_ISDIGIT | CTYPE_ISXDIGIT,
    /* 0x38 '8'  */ CTYPE_ISDIGIT | CTYPE_ISXDIGIT,
    /* 0x39 '9'  */ CTYPE_ISDIGIT | CTYPE_ISXDIGIT,
    /* 0x3A ':'  */ 0,
    /* 0x3B ';'  */ 0,
    /* 0x3C '<'  */ 0,
    /* 0x3D '='  */ 0,
    /* 0x3E '>'  */ 0,
    /* 0x3F '?'  */ 0,
    /* 0x40 '@'  */ 0,
    /* 0x41 'A'  */ CTYPE_ISUPPER | CTYPE_ISXDIGIT,
    /* 0x42 'B'  */ CTYPE_ISUPPER | CTYPE_ISXDIGIT,
    /* 0x43 'C'  */ CTYPE_ISUPPER | CTYPE_ISXDIGIT,
    /* 0x44 'D'  */ CTYPE_ISUPPER | CTYPE_ISXDIGIT,
    /* 0x45 'E'  */ CTYPE_ISUPPER | CTYPE_ISXDIGIT,
    /* 0x46 'F'  */ CTYPE_ISUPPER | CTYPE_ISXDIGIT,
    /* 0x47 'G'  */ CTYPE_ISUPPER,
    /* 0x48 'H'  */ CTYPE_ISUPPER,
    /* 0x49 'I'  */ CTYPE_ISUPPER,
    /* 0x4A 'J'  */ CTYPE_ISUPPER,
    /* 0x4B 'K'  */ CTYPE_ISUPPER,
    /* 0x4C 'L'  */ CTYPE_ISUPPER,
    /* 0x4D 'M'  */ CTYPE_ISUPPER,
    /* 0x4E 'N'  */ CTYPE_ISUPPER,
    /* 0x4F 'O'  */ CTYPE_ISUPPER,
    /* 0x50 'P'  */ CTYPE_ISUPPER,
    /* 0x51 'Q'  */ CTYPE_ISUPPER,
    /* 0x52 'R'  */ CTYPE_ISUPPER,
    /* 0x53 'S'  */ CTYPE_ISUPPER,
    /* 0x54 'T'  */ CTYPE_ISUPPER,
    /* 0x55 'U'  */ CTYPE_ISUPPER,
    /* 0x56 'V'  */ CTYPE_ISUPPER,
    /* 0x57 'W'  */ CTYPE_ISUPPER,
    /* 0x58 'X'  */ CTYPE_ISUPPER,
    /* 0x59 'Y'  */ CTYPE_ISUPPER,
    /* 0x5A 'Z'  */ CTYPE_ISUPPER,
    /* 0x5B '['  */ 0,
    /* 0x5C '\\' */ 0,
    /* 0x5D ']'  */ 0,
    /* 0x5E '^'  */ 0,
    /* 0x5F '_'  */ 0,
    /* 0x60 '`'  */ 0,
    /* 0x61 'a'  */ CTYPE_ISLOWER | CTYPE_ISXDIGIT,
    /* 0x62 'b'  */ CTYPE_ISLOWER | CTYPE_ISXDIGIT,
    /* 0x63 'c'  */ CTYPE_ISLOWER | CTYPE_ISXDIGIT,
    /* 0x64 'd'  */ CTYPE_ISLOWER | CTYPE_ISXDIGIT,
    /* 0x65 'e'  */ CTYPE_ISLOWER | CTYPE_ISXDIGIT,
    /* 0x66 'f'  */ CTYPE_ISLOWER | CTYPE_ISXDIGIT,
    /* 0x67 'g'  */ CTYPE_ISLOWER | CTYPE_ISXDIGIT,
    /* 0x68 'h'  */ CTYPE_ISLOWER,
    /* 0x69 'i'  */ CTYPE_ISLOWER,
    /* 0x6A 'j'  */ CTYPE_ISLOWER,
    /* 0x6B 'k'  */ CTYPE_ISLOWER,
    /* 0x6C 'l'  */ CTYPE_ISLOWER,
    /* 0x6D 'm'  */ CTYPE_ISLOWER,
    /* 0x6E 'n'  */ CTYPE_ISLOWER,
    /* 0x6F 'o'  */ CTYPE_ISLOWER,
    /* 0x70 'p'  */ CTYPE_ISLOWER,
    /* 0x71 'q'  */ CTYPE_ISLOWER,
    /* 0x72 'r'  */ CTYPE_ISLOWER,
    /* 0x73 's'  */ CTYPE_ISLOWER,
    /* 0x74 't'  */ CTYPE_ISLOWER,
    /* 0x75 'u'  */ CTYPE_ISLOWER,
    /* 0x76 'v'  */ CTYPE_ISLOWER,
    /* 0x77 'w'  */ CTYPE_ISLOWER,
    /* 0x78 'x'  */ CTYPE_ISLOWER,
    /* 0x79 'y'  */ CTYPE_ISLOWER,
    /* 0x7A 'z'  */ CTYPE_ISLOWER,
    /* 0x7B '{'  */ 0,
    /* 0x7C '|'  */ 0,
    /* 0x7D '}'  */ 0,
    /* 0x7E '~'  */ 0,
    /* 0x7F ''   */ CTYPE_ISCONTROL,
    /* 0x80 ''   */ 0,
    /* 0x81 ''   */ 0,
    /* 0x82 ''   */ 0,
    /* 0x83 ''   */ 0,
    /* 0x84 ''   */ 0,
    /* 0x85 ''   */ 0,
    /* 0x86 ''   */ 0,
    /* 0x87 ''   */ 0,
    /* 0x88 ''   */ 0,
    /* 0x89 ''   */ 0,
    /* 0x8A ''   */ 0,
    /* 0x8B ''   */ 0,
    /* 0x8C ''   */ 0,
    /* 0x8D ''   */ 0,
    /* 0x8E ''   */ 0,
    /* 0x8F ''   */ 0,
    /* 0x90 ''   */ 0,
    /* 0x91 ''   */ 0,
    /* 0x92 ''   */ 0,
    /* 0x93 ''   */ 0,
    /* 0x94 ''   */ 0,
    /* 0x95 ''   */ 0,
    /* 0x96 ''   */ 0,
    /* 0x97 ''   */ 0,
    /* 0x98 ''   */ 0,
    /* 0x99 ''   */ 0,
    /* 0x9A ''   */ 0,
    /* 0x9B ''   */ 0,
    /* 0x9C ''   */ 0,
    /* 0x9D ''   */ 0,
    /* 0x9E ''   */ 0,
    /* 0x9F ''   */ 0,
    /* 0xA0 ''   */ 0,
    /* 0xA1 ''   */ 0,
    /* 0xA2 ''   */ 0,
    /* 0xA3 ''   */ 0,
    /* 0xA4 ''   */ 0,
    /* 0xA5 ''   */ 0,
    /* 0xA6 ''   */ 0,
    /* 0xA7 ''   */ 0,
    /* 0xA8 ''   */ 0,
    /* 0xA9 ''   */ 0,
    /* 0xAA ''   */ 0,
    /* 0xAB ''   */ 0,
    /* 0xAC ''   */ 0,
    /* 0xAD ''   */ 0,
    /* 0xAE ''   */ 0,
    /* 0xAF ''   */ 0,
    /* 0xB0 ''   */ 0,
    /* 0xB1 ''   */ 0,
    /* 0xB2 ''   */ 0,
    /* 0xB3 ''   */ 0,
    /* 0xB4 ''   */ 0,
    /* 0xB5 ''   */ 0,
    /* 0xB6 ''   */ 0,
    /* 0xB7 ''   */ 0,
    /* 0xB8 ''   */ 0,
    /* 0xB9 ''   */ 0,
    /* 0xBA ''   */ 0,
    /* 0xBB ''   */ 0,
    /* 0xBC ''   */ 0,
    /* 0xBD ''   */ 0,
    /* 0xBE ''   */ 0,
    /* 0xBF ''   */ 0,
    /* 0xC0 ''   */ 0,
    /* 0xC1 ''   */ 0,
    /* 0xC2 ''   */ 0,
    /* 0xC3 ''   */ 0,
    /* 0xC4 ''   */ 0,
    /* 0xC5 ''   */ 0,
    /* 0xC6 ''   */ 0,
    /* 0xC7 ''   */ 0,
    /* 0xC8 ''   */ 0,
    /* 0xC9 ''   */ 0,
    /* 0xCA ''   */ 0,
    /* 0xCB ''   */ 0,
    /* 0xCC ''   */ 0,
    /* 0xCD ''   */ 0,
    /* 0xCE ''   */ 0,
    /* 0xCF ''   */ 0,
    /* 0xD0 ''   */ 0,
    /* 0xD1 ''   */ 0,
    /* 0xD2 ''   */ 0,
    /* 0xD3 ''   */ 0,
    /* 0xD4 ''   */ 0,
    /* 0xD5 ''   */ 0,
    /* 0xD6 ''   */ 0,
    /* 0xD7 ''   */ 0,
    /* 0xD8 ''   */ 0,
    /* 0xD9 ''   */ 0,
    /* 0xDA ''   */ 0,
    /* 0xDB ''   */ 0,
    /* 0xDC '\ ' */ 0,
    /* 0xDD ''   */ 0,
    /* 0xDE ''   */ 0,
    /* 0xDF ''   */ 0,
    /* 0xE0 ''   */ 0,
    /* 0xE1 ''   */ 0,
    /* 0xE2 ''   */ 0,
    /* 0xE3 ''   */ 0,
    /* 0xE4 ''   */ 0,
    /* 0xE5 ''   */ 0,
    /* 0xE6 ''   */ 0,
    /* 0xE7 ''   */ 0,
    /* 0xE8 ''   */ 0,
    /* 0xE9 ''   */ 0,
    /* 0xEA ''   */ 0,
    /* 0xEB ''   */ 0,
    /* 0xEC ''   */ 0,
    /* 0xED ''   */ 0,
    /* 0xEE ''   */ 0,
    /* 0xEF ''   */ 0,
    /* 0xF0 ''   */ 0,
    /* 0xF1 ''   */ 0,
    /* 0xF2 ''   */ 0,
    /* 0xF3 ''   */ 0,
    /* 0xF4 ''   */ 0,
    /* 0xF5 ''   */ 0,
    /* 0xF6 ''   */ 0,
    /* 0xF7 ''   */ 0,
    /* 0xF8 ''   */ 0,
    /* 0xF9 ''   */ 0,
    /* 0xFA ''   */ 0,
    /* 0xFB ''   */ 0,
    /* 0xFC ''   */ 0,
    /* 0xFD ''   */ 0,
    /* 0xFE ''   */ 0,
    /* 0xFF ''   */ 0,
};
