
char st_staffroll_txt[] =
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(BLUE) "Dr. Mario Creative Staff" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(GREEN) "Original Concept" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Gunpei Yokoi" MSG_NEWLINE
    "Takahiro Harada" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(CYAN) "Game Design" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Hitoshi Yamagami" MSG_NEWLINE
    "Kazushi Maeda" MSG_NEWLINE
    "Yohei Fujigawa" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(ORANGE) "Programmers" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Yasunori Kobayashi" MSG_NEWLINE
    "Kazunori Hasegawa" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(GREEN) "CG Designers" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Yohei Fujigawa" MSG_NEWLINE
    "Akio Saito" MSG_NEWLINE
    "Shinichi Takehiro" MSG_NEWLINE
    "Takehiro Ishikawa" MSG_NEWLINE
    "Nozomi Kawai" MSG_NEWLINE
    "Tomoki Oda" MSG_NEWLINE
    "Toshiyuki Matsuda" MSG_NEWLINE
    "Yukio Tanaka" MSG_NEWLINE
    "Toyohide Ando" MSG_NEWLINE
    "Taichi Sasaki" MSG_NEWLINE
    "Takatoshi Anbe" MSG_NEWLINE
    "Tomoaki Yamaguchi" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(CYAN) "Art Director" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Toyo Ashida" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(ORANGE) "Original Character Art" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Yukio Ebisawa" MSG_NEWLINE
    "Toyo Ashida" MSG_NEWLINE
    "Hiroshi Takeuchi" MSG_NEWLINE
    "Ayako Kurada" MSG_NEWLINE
    "Hatsue Koizumi" MSG_NEWLINE
    "Mariko Oka" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(GREEN) "Character Animation" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Kiyomi Ishiwata" MSG_NEWLINE
    "Mami Yamaguchi" MSG_NEWLINE
    "Hatsue Koizumi" MSG_NEWLINE
    "Hideki Nagamachi" MSG_NEWLINE
    "Shingo Kuragari" MSG_NEWLINE
    "Masahito Onoda" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(CYAN) "Original Background Art" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Toyo Ashida" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(ORANGE) "Background Colorist" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Yuki Enatsu" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(GREEN) "Package Art" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Sachiko Nakamichi" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(CYAN) "Original Sound Composer" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Hirokazu Tanaka" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(ORANGE) "Sound Composer" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Manabu Fujiki" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(GREEN) "Music Composer" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Seiichi Tokunaga" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(CYAN) "Debug Staff" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Super Mario Club" MSG_NEWLINE
    "Hifumi Miyazaki" MSG_NEWLINE
    "Kayo Komaki" MSG_NEWLINE
    "Fumiaki Shimada" MSG_NEWLINE
    "Satomi Hasuike" MSG_NEWLINE
    "Tomoharu Hizakae" MSG_NEWLINE
    "Kanako Fujisawa" MSG_NEWLINE
    "Toshiaki Suzuki" MSG_NEWLINE
    "Satoru Uno" MSG_NEWLINE
    "Koichi Torii" MSG_NEWLINE
    "Tomoko Yuasa" MSG_NEWLINE
    "Yasunori Shibayama" MSG_NEWLINE
    "Takahiro Nakamura" MSG_NEWLINE
    "Kotaro Haneda" MSG_NEWLINE
    "Shohei Zenjo" MSG_NEWLINE
    "Yoshihito Tsuji" MSG_NEWLINE
    "Takahiro Onishi" MSG_NEWLINE
    "Tatsuro Sawada" MSG_NEWLINE
    "Takehiko Asaka" MSG_NEWLINE
    "Tomokazu Suganuma" MSG_NEWLINE
    "Takuya Inoue" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(ORANGE) "Special Thanks" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Takehiro Izushi" MSG_NEWLINE
    "Masao Yamamoto" MSG_NEWLINE
    "Minoru Arakawa" MSG_NEWLINE
    "Manabu ''Mike'' Fukuda" MSG_NEWLINE
    "Sakae Yamazaki" MSG_NEWLINE
    "Fontworks Japan" MSG_NEWLINE
    "Nintendo R&D 1" MSG_NEWLINE
#if VERSION_US || VERSION_GW
    "Newcom Co., Ltd." MSG_NEWLINE
#elif VERSION_CN
    "Newcom Co.， Ltd." MSG_NEWLINE
#endif
    MSG_NEWLINE
    MSG_COLOR(GREEN) "Voice Acting" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Charles Martinet" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(CYAN) "Localization" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Tim O'Leary" MSG_NEWLINE
    "Bill Trinen" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(ORANGE) "Localization Management" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Jeff Miller" MSG_NEWLINE
    "Leslie Swan" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(GREEN) "Testing and Debug" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Michael Kelbaugh" MSG_NEWLINE
    "NOA Debug Staff" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(CYAN) "Assistant" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Azusa Tajima" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(ORANGE) "Directors" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Hitoshi Yamagami" MSG_NEWLINE
    "Yoshiyuki Kato" MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(GREEN) "Producers" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Genyo Takeda" MSG_NEWLINE
    "Junichi Yakahi" MSG_NEWLINE
    MSG_NEWLINE
#if VERSION_US || VERSION_GW
    MSG_COLOR(ORANGE) "Created By" MSG_NEWLINE
    "Nintendo Co., Ltd." MSG_NEWLINE
#elif VERSION_CN
    MSG_COLOR(CYAN) "Created By" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "Nintendo Co., Ltd." MSG_NEWLINE
    MSG_NEWLINE
    MSG_COLOR(ORANGE) "China Production" MSG_COLOR(ORANGE2) MSG_NEWLINE
    "iQue Engineering" MSG_NEWLINE
#endif
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_NEWLINE
    MSG_END;

char mes_mo1_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Aa...aa..aachoo!" MSG_NEWLINE
    "Suddenly, flu" MSG_NEWLINE
    "season has struck!"
#elif VERSION_CN
    "啊…啊…啊嘁！" MSG_NEWLINE
    "忽然，流感季节到来了！"
#endif
    MSG_END;

char mes_mo1_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "And so Dr. Mario" MSG_NEWLINE
    "rushes about, curing" MSG_NEWLINE
    "patients all day long."
#elif VERSION_CN
    "所以，马力欧医生一天到晚" MSG_NEWLINE
    "四处奔波，为大家治病。"
#endif
    MSG_END;

struct_mes_data mes_mo1_data[3] = {
    { ARRAY_COUNT(mes_mo1_data) - 1, NULL },
    { 0x64, mes_mo1_1 },
    { 0x19F, mes_mo1_2},
};

char mes_wo1_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Aa...aa..aachoo!" MSG_NEWLINE
    "Suddenly, flu" MSG_NEWLINE
    "season has struck!"
#elif VERSION_CN
    "啊…啊…啊嘁！" MSG_NEWLINE
    "忽然，流感季节到来了！"
#endif
    MSG_END;

char mes_wo1_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "And so Dr. Mario" MSG_NEWLINE
    "rushes about, curing" MSG_NEWLINE
    "patients all day long."
#elif VERSION_CN
    "所以，马力欧医生一天到晚" MSG_NEWLINE
    "四处奔波，为大家治病。"
#endif
    MSG_END;

char mes_wo1_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(ORANGE2) "Wario" MSG_COLOR(BLACK) ": " MSG_COLOR(ORANGE2) "It's-a me," MSG_NEWLINE
    "Wario! I'm so bored."
#elif VERSION_CN
    MSG_COLOR(ORANGE2) "瓦力欧" MSG_COLOR(ORANGE2) "：" MSG_COLOR(ORANGE2) "是我，" MSG_NEWLINE
    "瓦力欧！我太闷了。"
#endif
    MSG_END;

struct_mes_data mes_wo1_data[4] = {
    { ARRAY_COUNT(mes_wo1_data) - 1, NULL },
    { 0x64, mes_wo1_1 },
    { 0x19E, mes_wo1_2 },
    { 0x444, mes_wo1_3 },
};

char mes_o2_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Octo" MSG_COLOR(BLACK) ": " MSG_COLOR(GREEN) "Ohhh..." MSG_NEWLINE
    "My achin' head." MSG_NEWLINE
    "Help me out, Doc."
#elif VERSION_CN
    MSG_COLOR(GREEN) "八爪怪" MSG_COLOR(GREEN) "：" MSG_COLOR(GREEN) "啊啊…" MSG_NEWLINE
    "我头好疼。" MSG_NEWLINE
    "请帮帮我，医生。"
#endif
    MSG_END;

char mes_o2_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Can Dr. Mario" MSG_NEWLINE
    "help poor Octo?"
#elif VERSION_CN
    "马力欧医生能帮助可怜的" MSG_NEWLINE
    "八爪怪吗？"
#endif
    MSG_END;

char mes_o2_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "He's getting out" MSG_NEWLINE
    "his Megavitamins."
#elif VERSION_CN
    "他缺乏大剂量维生素。"
#endif
    MSG_END;

char mes_o2_3a[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "As long as he's got" MSG_NEWLINE
    "Megavitamins, he" MSG_NEWLINE
    "can cure anything."
#elif VERSION_CN
    "只要他获得大剂量维生素，" MSG_NEWLINE
    "他就能救治所有的人。"
#endif
    MSG_END;

char mes_o2_4[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(ORANGE2) "Wario" MSG_COLOR(BLACK) ": " MSG_COLOR(ORANGE2) "Megavitamins!" MSG_NEWLINE
    "I'll be rich if I can" MSG_NEWLINE
    "get my hands on those."
#elif VERSION_CN
    MSG_COLOR(ORANGE2) "瓦力欧" MSG_COLOR(ORANGE2) "：" MSG_COLOR(ORANGE2) "大剂量维生素！" MSG_NEWLINE
    "只要拥有那些我就发财了。"
#endif
    MSG_END;

char mes_o2_5[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Mad Scienstein" MSG_COLOR(BLACK) ": " MSG_COLOR(GREEN) "At" MSG_NEWLINE
    "last! I know where" MSG_NEWLINE
    "to get Megavitamins."
#elif VERSION_CN
    MSG_COLOR(GREEN) "科学狂人" MSG_COLOR(GREEN) "：" MSG_COLOR(GREEN) "终于！" MSG_NEWLINE
    "我知道在哪儿得到大剂量" MSG_NEWLINE
    "维生素了。"
#endif
    MSG_END;

struct_mes_data mes_o2_data[7] = {
    { ARRAY_COUNT(mes_o2_data) - 1, NULL },
    { 1, mes_o2_1 },
    { 0xF6, mes_o2_2 },
    { 0x1D6, mes_o2_3 },
    { 0x2A8, mes_o2_3a },
    { 0x3FC, mes_o2_4 },
    { 0x578, mes_o2_5 },
};

char mes_o3_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(MAGENTA) "???" MSG_COLOR(BLACK) ": " MSG_COLOR(MAGENTA) "Just what I've" MSG_NEWLINE
    "been looking for..." MSG_NEWLINE
    "Megavitamins."
#elif VERSION_CN
    MSG_COLOR(MAGENTA) "？？？" MSG_COLOR(MAGENTA) "：" MSG_NEWLINE
    MSG_COLOR(MAGENTA) "正是我在寻找的…" MSG_NEWLINE
    "大剂量维生素。"
#endif
    MSG_END;

char mes_o3_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(MAGENTA) "What are you" MSG_NEWLINE
    "waiting for? Go" MSG_NEWLINE
    "and steal them!"
#elif VERSION_CN
    MSG_COLOR(MAGENTA) "你还在等什么？" MSG_NEWLINE
    "去把它们偷过来！"
#endif
    MSG_END;

struct_mes_data mes_o3_data[3] = {
    { ARRAY_COUNT(mes_o3_data) - 1, NULL },
    { 0x80, mes_o3_1 },
    { 0x17C, mes_o3_2 },
};

char mes_01_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Dr. Mario returns" MSG_NEWLINE
    "home to take a" MSG_NEWLINE
    "well-deserved rest."
#elif VERSION_CN
    "马力欧医生回到家" MSG_NEWLINE
    "好好休息了一下。"
#endif
    MSG_END;

char mes_01_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "But wait, he's leaving" MSG_NEWLINE
    "again so soon?"
#elif VERSION_CN
    "但是，等等，他这么快又要" MSG_NEWLINE
    "离开了吗？"
#endif
    MSG_END;

char mes_01_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Look! Going into" MSG_NEWLINE
    "Dr. Mario's house..." MSG_NEWLINE
    "it's Mad Scienstein!"
#elif VERSION_CN
    "看！" MSG_NEWLINE
    "有人进了马力欧医生的家…" MSG_NEWLINE
    "那是科学狂人！"
#endif
    MSG_END;

char mes_01_4[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "This is terrible!" MSG_NEWLINE
    "He's stolen the" MSG_NEWLINE
    "Megavitamins!"
#elif VERSION_CN
    "大事不好！" MSG_NEWLINE
    "他偷走了大剂量维生素！"
#endif
    MSG_END;

char mes_01_5[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Wario sees him and" MSG_NEWLINE
    "says: " MSG_COLOR(ORANGE2) "Hold it, you!" MSG_NEWLINE
    "Those belong to me."
#elif VERSION_CN
    "瓦力欧看见了他" MSG_NEWLINE
    "并喊道：" MSG_COLOR(ORANGE2) "你给我站住！" MSG_NEWLINE
    "那些是我的。"
#endif
    MSG_END;

char mes_01_6[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Dr. Mario is back." MSG_NEWLINE
    "What a shock! The" MSG_NEWLINE
    "Megavitamins are gone."
#elif VERSION_CN
    "马力欧医生回来了。" MSG_NEWLINE
    "太令人吃惊了！" MSG_NEWLINE
    "大剂量维生素不见了。"
#endif
    MSG_END;

char mes_01_7[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Dr. Mario spots Wario" MSG_NEWLINE
    "and says: " MSG_COLOR(ORANGE) "Thief! You" MSG_NEWLINE
    "won't get away!"
#elif VERSION_CN
    "马力欧医生发现了瓦力欧" MSG_NEWLINE
    "并说：" MSG_COLOR(ORANGE) "小偷！" MSG_NEWLINE
    "我不会让你逃走！"
#endif
    MSG_END;

struct_mes_data mes_01_data[8] = {
    { ARRAY_COUNT(mes_01_data) - 1, NULL },
    { 0x65, mes_01_1 },
    { 0x190, mes_01_2 },
    { 0x26E, mes_01_3 },
    { 0x394, mes_01_4 },
    { 0x49C, mes_01_5 },
    { 0x755, mes_01_6 },
    { 0x898, mes_01_7 },
};

char mes_m02a_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Dr. Mario stops Wario" MSG_NEWLINE
    "but finds he doesn't" MSG_NEWLINE
    "have the Megavitamins."
#elif VERSION_CN
    "马力欧医生阻止了瓦力欧" MSG_NEWLINE
    "但是发现他并没有" MSG_NEWLINE
    "大剂量维生素。"
#endif
    MSG_END;

char mes_m02a_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Hey! There's the" MSG_NEWLINE
    "thief! He's getting" MSG_NEWLINE
    "away! After him!"
#elif VERSION_CN
    "嘿！小偷在那儿！" MSG_NEWLINE
    "他逃走了！" MSG_NEWLINE
    "快追上他！"
#endif
    MSG_END;

struct_mes_data mes_m02a_data[3] = {
    { ARRAY_COUNT(mes_m02a_data) - 1, NULL },
    { 1, mes_m02a_1 },
    { 0x10E, mes_m02a_2 },
};

char mes_w02a_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(ORANGE2) "Wario" MSG_COLOR(BLACK) ": " MSG_COLOR(ORANGE2) "It's not me." MSG_NEWLINE
    "I didn't steal the" MSG_NEWLINE
    "Megavitamins."
#elif VERSION_CN
    MSG_COLOR(ORANGE2) "瓦力欧" MSG_COLOR(ORANGE2) "：" MSG_COLOR(ORANGE2) "不是我。" MSG_NEWLINE
    "我没有偷" MSG_NEWLINE
    "大剂量维生素。"
#endif
    MSG_END;

char mes_w02a_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(ORANGE2) "There! That's him!" MSG_NEWLINE
    "He's the one. Stop!" MSG_NEWLINE
    "Those are Wario's!"
#elif VERSION_CN
    MSG_COLOR(ORANGE2) "那里！是他！" MSG_NEWLINE
    "他是小偷！站住！" MSG_NEWLINE
    "东西是瓦力欧的！"
#endif
    MSG_END;

struct_mes_data mes_w02a_data[3] = {
    { ARRAY_COUNT(mes_w02a_data) - 1, NULL },
    { 1, mes_w02a_1 },
    { 0xCC, mes_w02a_2 },
};

char mes_m02b_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Mad Scienstein" MSG_COLOR(BLACK) ":" MSG_NEWLINE
    MSG_COLOR(GREEN) "Here's the plan," MSG_NEWLINE
    "pss...pss...pss...."
#elif VERSION_CN
    MSG_COLOR(GREEN) "科学狂人" MSG_COLOR(GREEN) "：" MSG_NEWLINE
    MSG_COLOR(GREEN) "这是计划，" MSG_NEWLINE
    "噼兹…噼兹…噼兹…"
#endif
    MSG_END;

char mes_m02b_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Dr. Mario and Wario" MSG_NEWLINE
    "chase after the" MSG_NEWLINE
    "Megavitamins."
#elif VERSION_CN
    "马力欧医生和瓦力欧追赶着" MSG_NEWLINE
    "大剂量维生素。"
#endif
    MSG_END;

char mes_m02b_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Mad Scienstein" MSG_COLOR(BLACK) ":" MSG_NEWLINE
    MSG_COLOR(GREEN) "So, the rest is" MSG_NEWLINE
    "up to you!"
#elif VERSION_CN
    MSG_COLOR(GREEN) "科学狂人" MSG_COLOR(GREEN) "：" MSG_NEWLINE
    MSG_COLOR(GREEN) "所以，下面" MSG_NEWLINE
    "就交给你了！"
#endif
    MSG_END;

char mes_m02b_4[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Spearhead" MSG_COLOR(BLACK) ":" MSG_NEWLINE
    MSG_COLOR(GREEN) "I won't let you..."
#elif VERSION_CN
    MSG_COLOR(GREEN) "矛头" MSG_COLOR(GREEN) "：" MSG_NEWLINE
    MSG_COLOR(GREEN) "我不会让你…"
#endif
    MSG_END;

char mes_m02b_5[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "POW! Wario runs" MSG_NEWLINE
    "over him and" MSG_NEWLINE
    "keeps on going."
#elif VERSION_CN
    "砰！瓦力欧超过了他，" MSG_NEWLINE
    "还在继续往前跑。"
#endif
    MSG_END;

char mes_m02b_6[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Spearhead" MSG_COLOR(BLACK) ": " MSG_COLOR(GREEN) "I..." MSG_NEWLINE
    "I won't let you" MSG_NEWLINE
    "take one more step!"
#elif VERSION_CN
    MSG_COLOR(GREEN) "矛头" MSG_COLOR(GREEN) "：" MSG_COLOR(GREEN) "我…" MSG_NEWLINE
    "我不会让你" MSG_NEWLINE
    "再多前进一步！"
#endif
    MSG_END;

struct_mes_data mes_m02b_data[7] = {
    { ARRAY_COUNT(mes_m02b_data) - 1, NULL },
    { 0x3C, mes_m02b_1 },
    { 0xFA, mes_m02b_2 },
    { 0x206, mes_m02b_3 },
    { 0x2B4, mes_m02b_4 },
    { 0x368, mes_m02b_5 },
    { 0x46A, mes_m02b_6 },
};

char mes_w02b_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Mad Scienstein" MSG_NEWLINE
    "scurries away."
#elif VERSION_CN
    "科学狂人" MSG_NEWLINE
    "急忙逃走。"
#endif
    MSG_END;

char mes_w02b_1a[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Wario and Dr. Mario" MSG_NEWLINE
    "chase after the" MSG_NEWLINE
    "Megavitamins."
#elif VERSION_CN
    "瓦力欧和马力欧医生追赶着" MSG_NEWLINE
    "大剂量维生素。"
#endif
    MSG_END;

char mes_w02b_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "There's a tree and" MSG_NEWLINE
    "Wario can't stop" MSG_NEWLINE
    "in time! BAM!"
#elif VERSION_CN
    "有棵树！" MSG_NEWLINE
    "瓦力欧没能及时停住脚！" MSG_NEWLINE
    "嘣！"
#endif
    MSG_END;

char mes_w02b_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Spearhead" MSG_COLOR(BLACK) ": " MSG_COLOR(GREEN) "Get ready." MSG_NEWLINE
    "You're going to pay" MSG_NEWLINE
    "for that mistake!"
#elif VERSION_CN
    MSG_COLOR(GREEN) "矛头" MSG_COLOR(GREEN) "：" MSG_COLOR(GREEN) "给我瞧。" MSG_NEWLINE
    "你会为此付出代价的！"
#endif
    MSG_END;

struct_mes_data mes_w02b_data[5] = {
    { ARRAY_COUNT(mes_w02b_data) - 1, NULL },
    { 1, mes_w02b_1 },
    { 0xC8, mes_w02b_1a },
    { 0x19E, mes_w02b_2 },
    { 0x2AC, mes_w02b_3 },
};

char mes_m03_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "The chase continues" MSG_NEWLINE
    "into the deep, dark" MSG_NEWLINE
    "forest."
#elif VERSION_CN
    "追赶还在继续…" MSG_NEWLINE
    "他们来到一片" MSG_NEWLINE
    "黑暗幽深的森林。"
#endif
    MSG_END;

char mes_m03_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "This is so creepy." MSG_NEWLINE
    "I've got a bad" MSG_NEWLINE
    "feeling about this."
#elif VERSION_CN
    "这太令人毛骨悚然了。" MSG_NEWLINE
    "我有种不祥的预感。"
#endif
    MSG_END;

char mes_m03_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(ORANGE2) "Wario" MSG_COLOR(BLACK) ":" MSG_NEWLINE
    MSG_COLOR(ORANGE2) "Yikes!"
#elif VERSION_CN
    MSG_COLOR(ORANGE2) "瓦力欧" MSG_COLOR(ORANGE2) "：" MSG_NEWLINE
    MSG_COLOR(ORANGE2) "呀！"
#endif
    MSG_END;

char mes_m03_4[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Something slips" MSG_NEWLINE
    "down from up above."
#elif VERSION_CN
    "有什么东西" MSG_NEWLINE
    "从上面滑下来了。"
#endif
    MSG_END;

char mes_m03_5[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Webber" MSG_COLOR(BLACK) ": " MSG_COLOR(GREEN) "Simmer down." MSG_NEWLINE
    "You're about to become" MSG_NEWLINE
    "a nice snack for me!"
#elif VERSION_CN
    MSG_COLOR(GREEN) "镰刀牙" MSG_COLOR(GREEN) "：" MSG_COLOR(GREEN) "捉到了。" MSG_NEWLINE
    "你是我的盘中餐了！"
#endif
    MSG_END;

struct_mes_data mes_m03_data[6] = {
    { ARRAY_COUNT(mes_m03_data) - 1, NULL },
    { 5, mes_m03_1 },
    { 0x126, mes_m03_2 },
    { 0x252, mes_m03_3 },
    { 0x2EE, mes_m03_4 },
    { 0x3B4, mes_m03_5 },
};

char mes_w03_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Wario won't stop" MSG_NEWLINE
    "until he gets those " MSG_NEWLINE
    "Megavitamins."
#elif VERSION_CN
    "瓦力欧在得到大剂量维生素" MSG_NEWLINE
    "前是不会停下的。"
#endif
    MSG_END;

char mes_w03_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Mad Scienstein stops" MSG_NEWLINE
    "suddenly! Wario slides" MSG_NEWLINE
    "right by and..."
#elif VERSION_CN
    "科学狂人忽然停住了！" MSG_NEWLINE
    "瓦力欧从一旁溜过…"
#endif
    MSG_END;

char mes_w03_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Webber" MSG_COLOR(BLACK) ":" MSG_NEWLINE
    MSG_COLOR(GREEN) "Oh my - you don't" MSG_NEWLINE
    "look very tasty."
#elif VERSION_CN
    MSG_COLOR(GREEN) "镰刀牙" MSG_COLOR(GREEN) "：" MSG_NEWLINE
    MSG_COLOR(GREEN) "噢，老天…" MSG_NEWLINE
    "你看上去并不那么可口。"
#endif
    MSG_END;

struct_mes_data mes_w03_data[4] = {
    { ARRAY_COUNT(mes_w03_data) - 1, NULL },
    { 5, mes_w03_1 },
    { 0x14A, mes_w03_2 },
    { 0x2DA, mes_w03_3 },
};

char mes_m04_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Silky's out for a nice" MSG_NEWLINE
    "leisurely crawl..." MSG_NEWLINE
    "Look out behind you!"
#elif VERSION_CN
    "蚕宝宝出去散心了," MSG_NEWLINE
    "当心你的后面！"
#endif
    MSG_END;

char mes_m04_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Go, Silky, go!" MSG_NEWLINE
    "You'd better get" MSG_NEWLINE
    "out of the way."
#elif VERSION_CN
    "去，蚕宝宝！" MSG_NEWLINE
    "你最好让开。"
#endif
    MSG_END;

char mes_m04_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Whew, what a shock." MSG_NEWLINE
    "Glad to see that" MSG_NEWLINE
    "you're safe."
#elif VERSION_CN
    "呼，好险。" MSG_NEWLINE
    "非常高兴看见你安然无恙。"
#endif
    MSG_END;

char mes_m04_4[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Silky" MSG_COLOR(BLACK) ": " MSG_COLOR(GREEN) "Yikes!"
#elif VERSION_CN
    MSG_COLOR(GREEN) "蚕宝宝" MSG_COLOR(GREEN) "：" MSG_COLOR(GREEN) "呀！"
#endif
    MSG_END;

struct_mes_data mes_m04_data[5] = {
    { ARRAY_COUNT(mes_m04_data) - 1, NULL },
    { 5, mes_m04_1 },
    { 0x138, mes_m04_2 },
    { 0x320, mes_m04_3 },
    { 0x3E8, mes_m04_4 },
};

char mes_w04_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Look! It's Appleby." MSG_NEWLINE
    "He looks so happy with " MSG_NEWLINE
    "his big, shiny apple."
#elif VERSION_CN
    "看！那是苹果太郎。" MSG_NEWLINE
    "他带着那亮晶晶的大苹果" MSG_NEWLINE
    "看起来非常高兴。"
#endif
    MSG_END;

char mes_w04_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Look out! Here" MSG_NEWLINE
    "they come! What" MSG_NEWLINE
    "a racket!"
#elif VERSION_CN
    "当心！" MSG_NEWLINE
    "他们来了！" MSG_NEWLINE
    "真是一团糟啊！"
#endif
    MSG_END;

char mes_w04_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Appleby" MSG_COLOR(BLACK) ": " MSG_COLOR(GREEN) "Hey! " MSG_NEWLINE
    "Give me back " MSG_NEWLINE
    "my apple!"
#elif VERSION_CN
    MSG_COLOR(GREEN) "苹果太郎" MSG_COLOR(GREEN) "：" MSG_COLOR(GREEN) "嗨！ " MSG_NEWLINE
    "把我苹果还回来！"
#endif
    MSG_END;

struct_mes_data mes_w04_data[4] = {
    { ARRAY_COUNT(mes_w04_data) - 1, NULL },
    { 5, mes_w04_1 },
    { 0x12C, mes_w04_2 },
    { 0x28A, mes_w04_3 },
};

char mes_m05_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "A beautiful blue" MSG_NEWLINE
    "sea lies at the" MSG_NEWLINE
    "edge of the forest."
#elif VERSION_CN
    "一片湛蓝美丽的大海出现在" MSG_NEWLINE
    "森林的边缘。"
#endif
    MSG_END;

char mes_m05_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "A coconut " MSG_NEWLINE
    "falls from" MSG_NEWLINE
    "a tree and..."
#elif VERSION_CN
    "一颗椰子 " MSG_NEWLINE
    "从树上掉落，而且…"
#endif
    MSG_END;

char mes_m05_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Wario gets jabbed" MSG_NEWLINE
    "and swells up" MSG_NEWLINE
    "like a big balloon!"
#elif VERSION_CN
    "瓦力欧被戳到了并象个" MSG_NEWLINE
    "大气球一样膨胀起来！"
#endif
    MSG_END;

char mes_m05_4[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Jellybob" MSG_COLOR(BLACK) ":" MSG_NEWLINE
    MSG_COLOR(GREEN) "Shwoooo!"
#elif VERSION_CN
    MSG_COLOR(GREEN) "小海蛰" MSG_COLOR(GREEN) "：" MSG_NEWLINE
    MSG_COLOR(GREEN) "嗖！"
#endif
    MSG_END;

struct_mes_data mes_m05_data[5] = {
    { ARRAY_COUNT(mes_m05_data) - 1, NULL },
    { 5, mes_m05_1 },
    { 0xD2, mes_m05_2 },
    { 0x190, mes_m05_3 },
    { 0x28A, mes_m05_4 },
};

char mes_w05_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "A beautiful blue" MSG_NEWLINE
    "sea lies at the" MSG_NEWLINE
    "edge of the forest."
#elif VERSION_CN
    "一片湛蓝美丽的大海出现在" MSG_NEWLINE
    "森林的边缘。"
#endif
    MSG_END;

char mes_w05_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Watch out!" MSG_NEWLINE
    "There goes" MSG_NEWLINE
    "a coconut!"
#elif VERSION_CN
    "当心！" MSG_NEWLINE
    "有一个椰子！"
#endif
    MSG_END;

char mes_w05_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Uh-oh! Something's" MSG_NEWLINE
    "coming up out of" MSG_NEWLINE
    "the sea!"
#elif VERSION_CN
    "呜喔！有什么东西" MSG_NEWLINE
    "从海中过来了！"
#endif
    MSG_END;

char mes_w05_4[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Octo" MSG_COLOR(BLACK) ": " MSG_COLOR(GREEN) "Prepare" MSG_NEWLINE
    "to be punished!"
#elif VERSION_CN
    MSG_COLOR(GREEN) "八爪怪" MSG_COLOR(GREEN) "：" MSG_COLOR(GREEN) "准备好" MSG_NEWLINE
    "受到惩罚吧！"
#endif
    MSG_END;

struct_mes_data mes_w05_data[5] = {
    { ARRAY_COUNT(mes_w05_data) - 1, NULL },
    { 2, mes_w05_1 },
    { 0xDC, mes_w05_2 },
    { 0x1F0, mes_w05_3 },
    { 0x2E0, mes_w05_4 },
};

char mes_m06_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "There's a path among" MSG_NEWLINE
    "the clouds. There" MSG_NEWLINE
    "goes Mad Scienstein."
#elif VERSION_CN
    "白云中出现一条道路。" MSG_NEWLINE
    "科学狂人向那儿跑去。"
#endif
    MSG_END;

char mes_m06_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Wario comes" MSG_NEWLINE
    "floating by, and" MSG_NEWLINE
    "Helio pops him!"
#elif VERSION_CN
    "瓦力欧从一边飘过" MSG_NEWLINE
    "气球酷哥把他吹走了！"
#endif
    MSG_END;

char mes_m06_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(ORANGE2) "Wario" MSG_COLOR(BLACK) ": " MSG_COLOR(ORANGE2) "Why's this" MSG_NEWLINE
    "happening to me!?!"
#elif VERSION_CN
    MSG_COLOR(ORANGE2) "瓦力欧" MSG_COLOR(ORANGE2) "：" MSG_COLOR(ORANGE2) "我为什么" MSG_NEWLINE
    "会这样！？！"
#endif
    MSG_END;

char mes_m06_4[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Helio" MSG_COLOR(BLACK) ": " MSG_COLOR(GREEN) "Ha-ha! " MSG_NEWLINE
    "And you're next!"
#elif VERSION_CN
    MSG_COLOR(GREEN) "气球酷哥" MSG_COLOR(GREEN) "：" MSG_COLOR(GREEN) "哈…哈！" MSG_NEWLINE
    "下一个就是你！"
#endif
    MSG_END;

struct_mes_data mes_m06_data[5] = {
    { ARRAY_COUNT(mes_m06_data) - 1, NULL },
    { 5, mes_m06_1 },
    { 0x12C, mes_m06_2 },
    { 0x226, mes_m06_3 },
    { 0x302, mes_m06_4 },
};

char mes_w06_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Zzz...zzz...zzz." MSG_NEWLINE
    "It's nap time in" MSG_NEWLINE
    "the mountains."
#elif VERSION_CN
    "呼噜噜…呼噜噜。" MSG_NEWLINE
    "现在是山里的午休时间。"
#endif
    MSG_END;

char mes_w06_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Look out below!"
#elif VERSION_CN
    "当心下面！"
#endif
    MSG_END;

char mes_w06_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Lump" MSG_COLOR(BLACK) ":" MSG_NEWLINE
    MSG_COLOR(GREEN) "Ribbit."
#elif VERSION_CN
    MSG_COLOR(GREEN) "肥青蛙" MSG_COLOR(GREEN) "：" MSG_NEWLINE
    MSG_COLOR(GREEN) "呱呱。"
#endif
    MSG_END;

struct_mes_data mes_w06_data[4] = {
    { ARRAY_COUNT(mes_w06_data) - 1, NULL },
    { 5, mes_w06_1 },
    { 0x244, mes_w06_2 },
    { 0x2E4, mes_w06_3 },
};

char mes_07_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Clank, clank..." MSG_NEWLINE
    "What an odd noise..." MSG_NEWLINE
    "This can't be good."
#elif VERSION_CN
    "哐啷哐，哐啷哐…" MSG_NEWLINE
    "好奇怪的吵声…" MSG_NEWLINE
    "这不会是好事情。"
#endif
    MSG_END;

char mes_07_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Hammer-Bot" MSG_COLOR(BLACK) ":" MSG_NEWLINE
    MSG_COLOR(GREEN) "Intruders detected!" MSG_NEWLINE
    "Eliminate. Eliminate."
#elif VERSION_CN
    MSG_COLOR(GREEN) "铁锤人" MSG_COLOR(GREEN) "：" MSG_NEWLINE
    MSG_COLOR(GREEN) "发现入侵者！" MSG_NEWLINE
    "消灭！消灭！"
#endif
    MSG_END;

char mes_07_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "They all want the" MSG_NEWLINE
    "Megavitamins. Will" MSG_NEWLINE
    "anyone survive?"
#elif VERSION_CN
    "他们都想要大剂量维生素, " MSG_NEWLINE
    "会有人逃过此劫吗？"
#endif
    MSG_END;

char mes_07E_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Eliminate? But" MSG_NEWLINE
    "you've come too" MSG_NEWLINE
    "far to lose now."
#elif VERSION_CN
    "消灭？" MSG_NEWLINE
    "但是, 你现在离失败" MSG_NEWLINE
    "已经不远了。"
#endif
    MSG_END;

struct_mes_data mes_07_data[4] = {
    { ARRAY_COUNT(mes_07_data) - 1, NULL },
    { 0x74, mes_07_1 },
    { 0x232, mes_07_2 },
    { 0x2EF, mes_07_3 },
};

struct_mes_data mes_07E_data[4] = {
    { ARRAY_COUNT(mes_07E_data) - 1, NULL },
    { 0x74, mes_07_1 },
    { 0x232, mes_07_2 },
    { 0x2EF, mes_07E_3 },
};

char mes_08a_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Mad Scienstein is so" MSG_NEWLINE
    "stubborn. He won't" MSG_NEWLINE
    "return the vitamins!"
#elif VERSION_CN
    "科学狂人非常顽固," MSG_NEWLINE
    "他绝不交还维生素！"
#endif
    MSG_END;

struct_mes_data mes_08a_data[2] = {
    { ARRAY_COUNT(mes_08a_data) - 1, NULL },
    { 0x65, mes_08a_1 },
};

char mes_08Ea_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Mad Scienstein" MSG_NEWLINE
    "escapes into the " MSG_NEWLINE
    "castle! After him!"
#elif VERSION_CN
    "科学狂人逃进了" MSG_NEWLINE
    "一座城堡！" MSG_NEWLINE
    "跟上他！"
#endif
    MSG_END;

struct_mes_data mes_08Ea_data[2] = {
    { ARRAY_COUNT(mes_08Ea_data) - 1, NULL },
    { 0x65, mes_08Ea_1 },
};

char mes_08b_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Deep into the castle" MSG_NEWLINE
    "they go. Oh my!" MSG_NEWLINE
    "It's Rudy!"
#elif VERSION_CN
    "他们进入城堡深处。" MSG_NEWLINE
    "噢，天哪！" MSG_NEWLINE
    "是神秘像！"
#endif
    MSG_END;

char mes_08b_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(MAGENTA) "Rudy" MSG_COLOR(BLACK) ": " MSG_COLOR(MAGENTA) "Ha-ha-ha..." MSG_NEWLINE
    "The Megavitamins" MSG_NEWLINE
    "are mine!"
#elif VERSION_CN
    MSG_COLOR(MAGENTA) "神秘像" MSG_COLOR(MAGENTA) "：" MSG_COLOR(MAGENTA) "哈哈哈…" MSG_NEWLINE
    "大剂量维生素是我的了！"
#endif
    MSG_END;

struct_mes_data mes_08b_data[3] = {
    { ARRAY_COUNT(mes_08b_data) - 1, NULL },
    { 0x17D, mes_08b_1 },
    { 0x293, mes_08b_2 },
};

char mes_m09_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Is that the end" MSG_NEWLINE
    "of our story? Wait," MSG_NEWLINE
    "here comes Wario."
#elif VERSION_CN
    "这就是我们故事的结局吗? " MSG_NEWLINE
    "等一下，" MSG_NEWLINE
    "我瓦力欧来了。"
#endif
    MSG_END;

char mes_m09_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Gulp, gulp. Wario" MSG_NEWLINE
    "has eaten the" MSG_NEWLINE
    "Megavitamins!"
#elif VERSION_CN
    "咕噜，咕噜。 " MSG_NEWLINE
    "瓦力欧吃掉了大剂量维生素！"
#endif
    MSG_END;

char mes_m09_4[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(ORANGE2) "Vampire Wario" MSG_COLOR(BLACK) ":" MSG_NEWLINE
    MSG_COLOR(ORANGE2) "Bwaa haa haa."
#elif VERSION_CN
    MSG_COLOR(ORANGE2) "吸血鬼瓦力欧" MSG_COLOR(ORANGE2) "：" MSG_NEWLINE
    MSG_COLOR(ORANGE2) "哇哈哈。"
#endif
    MSG_END;

struct_mes_data mes_m09_data[4] = {
    { ARRAY_COUNT(mes_m09_data) - 1, NULL },
    { 0x70, mes_m09_2 },
    { 0x2F3, mes_m09_3 },
    { 0x3F2, mes_m09_4 },
};

char mes_w09_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Is that the end" MSG_NEWLINE
    "of our story? Wait," MSG_NEWLINE
    "here comes Dr. Mario."
#elif VERSION_CN
    "这就是我们故事的结局吗？" MSG_NEWLINE
    "等一下，" MSG_NEWLINE
    "我马力欧医生来了。"
#endif
    MSG_END;

char mes_w09_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Wario is escaping" MSG_NEWLINE
    "with the Megavitamins." MSG_NEWLINE
    "Whoa, he's tripped!"
#elif VERSION_CN
    "瓦力欧带着大剂量维生素" MSG_NEWLINE
    "逃走了。" MSG_NEWLINE
    "哇，他摔倒了！"
#endif
    MSG_END;

char mes_w09_4[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Oh no! Dr. Mario's " MSG_NEWLINE
    "swallowed them all" MSG_NEWLINE
    "and he's changing!"
#elif VERSION_CN
    "哦，不！" MSG_NEWLINE
    "马力欧医生把它们都吞了" MSG_NEWLINE
    "下去，他发生变化了！"
#endif
    MSG_END;

struct_mes_data mes_w09_data[4] = {
    { ARRAY_COUNT(mes_w09_data) - 1, NULL },
    { 0xA1, mes_w09_2 },
    { 0x1D6, mes_w09_3 },
    { 0x2BC, mes_w09_4 },
};

char mes_m0e1_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Rudy's been defeated" MSG_NEWLINE
    "and he looks terrible." MSG_NEWLINE
    "Aha! He's got a cold."
#elif VERSION_CN
    "神秘像被击败了，" MSG_NEWLINE
    "他看上去非常糟糕。" MSG_NEWLINE
    "啊哈！他得感冒了。"
#endif
    MSG_END;

char mes_m0e1_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "If it's a cold, I'll" MSG_NEWLINE
    "cure him. After all," MSG_NEWLINE
    "I'm Dr. Mario."
#elif VERSION_CN
    "如果是感冒，我就要治好他。" MSG_NEWLINE
    "归根到底，" MSG_NEWLINE
    "我是马力欧医生。"
#endif
    MSG_END;

char mes_m0e1_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Rudy's all better." MSG_NEWLINE
    "Now if he'll just" MSG_NEWLINE
    "stop stealing!"
#elif VERSION_CN
    "神秘像好多了。" MSG_NEWLINE
    "他应该不会再偷东西了！"
#endif
    MSG_END;

struct_mes_data mes_m0e1_data[4] = {
    { ARRAY_COUNT(mes_m0e1_data) - 1, NULL },
    { 0x14, mes_m0e1_1},
    { 0x17C, mes_m0e1_2},
    { 0x2BC, mes_m0e1_3},
};

char mes_m0e2_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(ORANGE2) "Wario" MSG_COLOR(BLACK) ": " MSG_COLOR(ORANGE2) "Darn! I" MSG_NEWLINE
    "won't forget this!"
#elif VERSION_CN
    MSG_COLOR(ORANGE2) "瓦力欧" MSG_COLOR(ORANGE2) "：" MSG_COLOR(ORANGE2) "混帐！" MSG_NEWLINE
    "我不会忘记这次的！"
#endif
    MSG_END;

char mes_m0e2_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Mad Scienstein" MSG_COLOR(BLACK) ":" MSG_NEWLINE
    MSG_COLOR(GREEN) "Master Rudy," MSG_NEWLINE
    "be strong!"
#elif VERSION_CN
    MSG_COLOR(GREEN) "科学狂人" MSG_COLOR(GREEN) "：" MSG_NEWLINE
    MSG_COLOR(GREEN) "神秘像主人，" MSG_NEWLINE
    "坚强些啊！"
#endif
    MSG_END;

char mes_m0e2_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(MAGENTA) "Rudy" MSG_COLOR(BLACK) ":" MSG_NEWLINE
    MSG_COLOR(MAGENTA) "Aaahh, owww..."
#elif VERSION_CN
    MSG_COLOR(MAGENTA) "神秘像" MSG_COLOR(MAGENTA) "：" MSG_NEWLINE
    MSG_COLOR(MAGENTA) "啊啊啊，哇哇哇…"
#endif
    MSG_END;

char mes_m0e2_4[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(GREEN) "Mad Scienstein" MSG_COLOR(BLACK) ":" MSG_NEWLINE
    MSG_COLOR(GREEN) "Oh, how" MSG_NEWLINE
    "heartrending..."
#elif VERSION_CN
    MSG_COLOR(GREEN) "科学狂人" MSG_COLOR(GREEN) "：" MSG_NEWLINE
    MSG_COLOR(GREEN) "哦，这是" MSG_NEWLINE
    "多么令人悲伤啊…"
#endif
    MSG_END;

char mes_m0e2_5[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "If it's a cold, I'll" MSG_NEWLINE
    "cure him. After all," MSG_NEWLINE
    "I'm Dr. Mario."
#elif VERSION_CN
    "如果是感冒，我就要治好他。" MSG_NEWLINE
    "归根到底，" MSG_NEWLINE
    "我是马力欧医生。"
#endif
    MSG_END;

char mes_m0e2_6[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Rudy's all better." MSG_NEWLINE
    "Now if he'll just" MSG_NEWLINE
    "stop stealing!"
#elif VERSION_CN
    "神秘像好多了。" MSG_NEWLINE
    "他应该不会再偷东西了！"
#endif
    MSG_END;

struct_mes_data mes_m0e2_data[7] = {
    { ARRAY_COUNT(mes_m0e2_data) - 1, NULL },
    { 0x28, mes_m0e2_1 },
    { 0x12C, mes_m0e2_2 },
    { 0x1E0, mes_m0e2_3 },
    { 0x28A, mes_m0e2_4 },
    { 0x30C, mes_m0e2_5 },
    { 0x486, mes_m0e2_6 },
};

char mes_m0e_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "It's time to go home." MSG_NEWLINE
    "Home, sweet home."
#elif VERSION_CN
    "是该回家的时候了。" MSG_NEWLINE
    "家，甜美的家。"
#endif
    MSG_END;

char mes_m0e_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Dr. Mario used" MSG_NEWLINE
    "the Megavitamins to" MSG_NEWLINE
    "cure everyone."
#elif VERSION_CN
    "马力欧医生用大剂量维生素" MSG_NEWLINE
    "治好了所有人。"
#endif
    MSG_END;

char mes_m0e_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "And they all" MSG_NEWLINE
    "lived happily" MSG_NEWLINE
    "ever after."
#elif VERSION_CN
    "从此以后, " MSG_NEWLINE
    "他们全都过着幸福的生活。" MSG_NEWLINE
#endif
    MSG_WAIT(3) MSG_H MSG_END;

struct_mes_data mes_m0e_data[4] = {
    { ARRAY_COUNT(mes_m0e_data) - 1, NULL },
    { 5, mes_m0e_1 },
    { 0x96, mes_m0e_2 },
    { 0x1B0, mes_m0e_3 },
};

char mes_w0e1_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "Wario's gotten rid" MSG_NEWLINE
    "of all obstacles." MSG_NEWLINE
    "Look at him grin."
#elif VERSION_CN
    "瓦力欧排除了所有的阻碍。" MSG_NEWLINE
    "看他笑的多开心。"
#endif
    MSG_END;

char mes_w0e1_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(ORANGE2) "Wario" MSG_COLOR(BLACK) ": " MSG_COLOR(ORANGE2) "Now the" MSG_NEWLINE
    "Megavitamins" MSG_NEWLINE
    "belong to me!"
#elif VERSION_CN
    MSG_COLOR(ORANGE2) "瓦力欧" MSG_COLOR(ORANGE2) "：" MSG_COLOR(ORANGE2) "现在" MSG_NEWLINE
    "大剂量维生素归我了！"
#endif
    MSG_END;

char mes_w0e1_3[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "But nothing's that" MSG_NEWLINE
    "easy. Mad Scienstein" MSG_NEWLINE
    "grabs them again."
#elif VERSION_CN
    "但没那么容易的事情。" MSG_NEWLINE
    "科学狂人又夺走了它们。"
#endif
    MSG_END;

struct_mes_data mes_w0e1_data[4] = {
    { ARRAY_COUNT(mes_w0e1_data) - 1, NULL },
    { 5, mes_w0e1_1 },
    { 0x118, mes_w0e1_2 },
    { 0x230, mes_w0e1_3 },
};

char mes_w0e2_1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "And the chase goes" MSG_NEWLINE
    "on and on. Will" MSG_NEWLINE
    "it ever end?"
#elif VERSION_CN
    "追逐周而复始。" MSG_NEWLINE
    "会有一个终点吗？"
#endif
    MSG_END;

char mes_w0e2_2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    "The end."
#elif VERSION_CN
    "剧终。"
#endif
    MSG_WAIT(3) MSG_H MSG_END;

struct_mes_data mes_w0e2_data[3] = {
    { ARRAY_COUNT(mes_w0e2_data) - 1, NULL },
    { 5, mes_w0e2_1 },
    { 0x126, mes_w0e2_2 },
};

char mes_ep1[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(MAGENTA) "???" MSG_COLOR(BLACK) ": " MSG_COLOR(MAGENTA) "That's the" MSG_NEWLINE
    "story, is it..."
#elif VERSION_CN
    MSG_COLOR(MAGENTA) "？？？" MSG_COLOR(MAGENTA) "：" MSG_COLOR(MAGENTA) "故事" MSG_NEWLINE
    "到此为止，是吗…"
#endif
    MSG_END;

char mes_ep2[] = MSG_H MSG_COLOR(BLACK)
#if VERSION_US || VERSION_GW
    MSG_COLOR(MAGENTA) "But they'll never make" MSG_NEWLINE
    "it this far. Hammer-" MSG_NEWLINE
    "Bot will stop them."
#elif VERSION_CN
    MSG_COLOR(MAGENTA) "但是他们将永远" MSG_NEWLINE
    "不可能来到这里。" MSG_NEWLINE
    "铁锤人会阻止他们的。"
#endif
    MSG_END;

struct_mes_data mes_ep_data[3] = {
    { ARRAY_COUNT(mes_ep_data) - 1, NULL },
    { 0x82, mes_ep1 },
    { 0x17C, mes_ep2 },
};

struct_mes_data *mes_data[] = {
    mes_mo1_data,
    mes_wo1_data,
    mes_o2_data,
    mes_o3_data,
    mes_01_data,
    mes_m02a_data,
    mes_w02a_data,
    mes_m02b_data,
    mes_w02b_data,
    mes_m03_data,
    mes_w03_data,
    mes_m04_data,
    mes_w04_data,
    mes_m05_data,
    mes_w05_data,
    mes_m06_data,
    mes_w06_data,
    mes_07_data,
    mes_08a_data,
    mes_08b_data,
    mes_m09_data,
    mes_w09_data,
    mes_m0e_data,
    mes_w0e1_data,
    mes_w0e2_data,
    mes_07E_data,
    mes_08Ea_data,
    mes_m0e1_data,
    mes_m0e2_data,
    mes_ep_data,
};
