#include "segment_symbols.h"
#include "rom_offsets.h"

/**
 * Original name: storyRomData
 */
RomOffsetPair storyRomData[] = {
    { SEGMENT_ROM_START(segment_coffee01), SEGMENT_ROM_END(segment_coffee01) },
    { SEGMENT_ROM_START(segment_menu_bg), SEGMENT_ROM_END(segment_menu_bg) },
    { SEGMENT_ROM_START(segment_menu_bg2), SEGMENT_ROM_END(segment_menu_bg2) },
    { SEGMENT_ROM_START(segment_waku), SEGMENT_ROM_END(segment_waku) },
    { SEGMENT_ROM_START(segment_waku2), SEGMENT_ROM_END(segment_waku2) },
    { SEGMENT_ROM_START(segment_title_all),SEGMENT_ROM_END(segment_title_all) },
    { SEGMENT_ROM_START(segment_title_bmp),SEGMENT_ROM_END(segment_title_bmp) },
};

/**
 * Original name: bgRomData
 */
RomOffsetPair bgRomData[] = {
    { 0x00000000, 0x00000000 },
    { SEGMENT_ROM_START(segment_story_bg03), SEGMENT_ROM_END(segment_story_bg03) },
    { SEGMENT_ROM_START(segment_story_bg01), SEGMENT_ROM_END(segment_story_bg01) },
    { SEGMENT_ROM_START(segment_story_bg09), SEGMENT_ROM_END(segment_story_bg09) },
    { SEGMENT_ROM_START(segment_story_bg02), SEGMENT_ROM_END(segment_story_bg02) },
    { SEGMENT_ROM_START(segment_story_bg07), SEGMENT_ROM_END(segment_story_bg07) },
    { SEGMENT_ROM_START(segment_story_bg05), SEGMENT_ROM_END(segment_story_bg05) },
    { SEGMENT_ROM_START(segment_story_bg10), SEGMENT_ROM_END(segment_story_bg10) },
    { SEGMENT_ROM_START(segment_story_bg11), SEGMENT_ROM_END(segment_story_bg11) },
    { SEGMENT_ROM_START(segment_story_bg11), SEGMENT_ROM_END(segment_story_bg11) },
    { SEGMENT_ROM_START(segment_story_bg11), SEGMENT_ROM_END(segment_story_bg11) },
    { 0x00000000, 0x00000000 },
    { 0x00000000, 0x00000000 },
    { SEGMENT_ROM_START(segment_story_bg03), SEGMENT_ROM_END(segment_story_bg03) },
    { SEGMENT_ROM_START(segment_story_bg01), SEGMENT_ROM_END(segment_story_bg01) },
    { SEGMENT_ROM_START(segment_story_bg09), SEGMENT_ROM_END(segment_story_bg09) },
    { SEGMENT_ROM_START(segment_story_bg02), SEGMENT_ROM_END(segment_story_bg02) },
    { SEGMENT_ROM_START(segment_story_bg08), SEGMENT_ROM_END(segment_story_bg08) },
    { SEGMENT_ROM_START(segment_story_bg04), SEGMENT_ROM_END(segment_story_bg04) },
    { SEGMENT_ROM_START(segment_story_bg10), SEGMENT_ROM_END(segment_story_bg10) },
    { SEGMENT_ROM_START(segment_story_bg11), SEGMENT_ROM_END(segment_story_bg11) },
    { SEGMENT_ROM_START(segment_story_bg11), SEGMENT_ROM_END(segment_story_bg11) },
    { SEGMENT_ROM_START(segment_story_bg11), SEGMENT_ROM_END(segment_story_bg11) },
    { 0x00000000, 0x00000000 },
};

/**
 * Original name: _romDataTbl
 */
RomOffsetPair _romDataTbl[] = {
    { SEGMENT_ROM_START(n64_wave_tables), SEGMENT_ROM_END(n64_wave_tables) },     // N64WaveTables
    { SEGMENT_ROM_START(n64_ptr_tables_v2), SEGMENT_ROM_END(n64_ptr_tables_v2) }, // N64PtrTables
    { SEGMENT_ROM_START(segment_172130), SEGMENT_ROM_END(segment_172130) },
    { SEGMENT_ROM_START(segment_172D60), SEGMENT_ROM_END(segment_172D60) },
    { SEGMENT_ROM_START(segment_177420), SEGMENT_ROM_END(segment_177420) },
    { SEGMENT_ROM_START(segment_17C1E0), SEGMENT_ROM_END(segment_17C1E0) },
    { SEGMENT_ROM_START(segment_17E090), SEGMENT_ROM_END(segment_17E090) },
    { SEGMENT_ROM_START(segment_184FF0), SEGMENT_ROM_END(segment_184FF0) },
    { SEGMENT_ROM_START(segment_1750C0), SEGMENT_ROM_END(segment_1750C0) },
    { SEGMENT_ROM_START(segment_179620), SEGMENT_ROM_END(segment_179620) },
    { SEGMENT_ROM_START(segment_17D130), SEGMENT_ROM_END(segment_17D130) },
    { SEGMENT_ROM_START(segment_181840), SEGMENT_ROM_END(segment_181840) },
    { SEGMENT_ROM_START(segment_186FF0), SEGMENT_ROM_END(segment_186FF0) },
    { SEGMENT_ROM_START(segment_188FF0), SEGMENT_ROM_END(segment_188FF0) },
    { SEGMENT_ROM_START(segment_189D40), SEGMENT_ROM_END(segment_189D40) },
    { SEGMENT_ROM_START(segment_17B790), SEGMENT_ROM_END(segment_17B790) },
    { SEGMENT_ROM_START(segment_18CB40), SEGMENT_ROM_END(segment_18CB40) },
    { SEGMENT_ROM_START(segment_18F160), SEGMENT_ROM_END(segment_18F160) },
    { SEGMENT_ROM_START(segment_1906E0), SEGMENT_ROM_END(segment_1906E0) },
    { SEGMENT_ROM_START(segment_1911D0), SEGMENT_ROM_END(segment_1911D0) },
    { SEGMENT_ROM_START(segment_1936C0), SEGMENT_ROM_END(segment_1936C0) },
    { SEGMENT_ROM_START(segment_1937F0), SEGMENT_ROM_END(segment_1937F0) },
    { SEGMENT_ROM_START(segment_194070), SEGMENT_ROM_END(segment_194070) },
    { SEGMENT_ROM_START(segment_194150), SEGMENT_ROM_END(segment_194150) },
    { SEGMENT_ROM_START(segment_194910), SEGMENT_ROM_END(segment_194910) },
    { SEGMENT_ROM_START(segment_195290), SEGMENT_ROM_END(segment_195290) },
    { SEGMENT_ROM_START(segment_18DB90), SEGMENT_ROM_END(segment_18DB90) },
    { SEGMENT_ROM_START(segment_anime_a), SEGMENT_ROM_END(segment_anime_a) },
    { SEGMENT_ROM_START(segment_anime_b), SEGMENT_ROM_END(segment_anime_b) },
    { SEGMENT_ROM_START(segment_anime_c), SEGMENT_ROM_END(segment_anime_c) },
    { SEGMENT_ROM_START(segment_anime_d), SEGMENT_ROM_END(segment_anime_d) },
    { SEGMENT_ROM_START(segment_anime_e), SEGMENT_ROM_END(segment_anime_e) },
    { SEGMENT_ROM_START(segment_anime_f), SEGMENT_ROM_END(segment_anime_f) },
    { SEGMENT_ROM_START(segment_anime_g), SEGMENT_ROM_END(segment_anime_g) },
    { SEGMENT_ROM_START(segment_anime_h), SEGMENT_ROM_END(segment_anime_h) },
    { SEGMENT_ROM_START(segment_anime_i), SEGMENT_ROM_END(segment_anime_i) },
    { SEGMENT_ROM_START(segment_anime_j), SEGMENT_ROM_END(segment_anime_j) },
    { SEGMENT_ROM_START(segment_anime_k), SEGMENT_ROM_END(segment_anime_k) },
    { SEGMENT_ROM_START(segment_anime_l), SEGMENT_ROM_END(segment_anime_l) },
    { SEGMENT_ROM_START(segment_anime_m), SEGMENT_ROM_END(segment_anime_m) },
    { SEGMENT_ROM_START(segment_anime_n), SEGMENT_ROM_END(segment_anime_n) },
    { SEGMENT_ROM_START(segment_anime_o), SEGMENT_ROM_END(segment_anime_o) },
    { SEGMENT_ROM_START(segment_anime_mario), SEGMENT_ROM_END(segment_anime_mario) },
    { SEGMENT_ROM_START(segment_anime_virus_b), SEGMENT_ROM_END(segment_anime_virus_b) },
    { SEGMENT_ROM_START(segment_anime_virus_r), SEGMENT_ROM_END(segment_anime_virus_r) },
    { SEGMENT_ROM_START(segment_anime_virus_y), SEGMENT_ROM_END(segment_anime_virus_y) },
    { SEGMENT_ROM_START(segment_anime_smog), SEGMENT_ROM_END(segment_anime_smog) },
    { SEGMENT_ROM_START(segment_game_al), SEGMENT_ROM_END(segment_game_al) },
    { SEGMENT_ROM_START(segment_game_p1), SEGMENT_ROM_END(segment_game_p1) },
    { SEGMENT_ROM_START(segment_game_p2), SEGMENT_ROM_END(segment_game_p2) },
    { SEGMENT_ROM_START(segment_game_p4), SEGMENT_ROM_END(segment_game_p4) },
    { SEGMENT_ROM_START(segment_game_ls), SEGMENT_ROM_END(segment_game_ls) },
    { SEGMENT_ROM_START(segment_game_item), SEGMENT_ROM_END(segment_game_item) },
    { SEGMENT_ROM_START(segment_game_etc), SEGMENT_ROM_END(segment_game_etc) },
    { SEGMENT_ROM_START(segment_menu_char), SEGMENT_ROM_END(segment_menu_char) },
    { SEGMENT_ROM_START(segment_menu_common), SEGMENT_ROM_END(segment_menu_common) },
    { SEGMENT_ROM_START(segment_menu_level), SEGMENT_ROM_END(segment_menu_level) },
    { SEGMENT_ROM_START(segment_menu_main), SEGMENT_ROM_END(segment_menu_main) },
    { SEGMENT_ROM_START(segment_menu_name), SEGMENT_ROM_END(segment_menu_name) },
    { SEGMENT_ROM_START(segment_menu_p2), SEGMENT_ROM_END(segment_menu_p2) },
    { SEGMENT_ROM_START(segment_menu_p4), SEGMENT_ROM_END(segment_menu_p4) },
    { SEGMENT_ROM_START(segment_menu_rank), SEGMENT_ROM_END(segment_menu_rank) },
    { SEGMENT_ROM_START(segment_menu_setup), SEGMENT_ROM_END(segment_menu_setup) },
    { SEGMENT_ROM_START(segment_menu_story), SEGMENT_ROM_END(segment_menu_story) },
    { SEGMENT_ROM_START(segment_menu_cont), SEGMENT_ROM_END(segment_menu_cont) },
    { SEGMENT_ROM_START(segment_menu_kasa), SEGMENT_ROM_END(segment_menu_kasa) },
    { SEGMENT_ROM_START(segment_tutorial_data), SEGMENT_ROM_END(segment_tutorial_data) },
};
